### ISSUE TITLE
How to Pass Parameters in Invoke 

### ISSUE THREAD

**Issue by coommark** [sochix/angular-signalr#1]
Hey! Awesome job. However I have a question, what if the server side function must be supplied with a parameter? For instance:

Public Tast SendMessage(string message)
{
   //do cool chat here
}

How do you invoke this?

**Comment by sochix** [comment]
Hi! Try this:
`SignalRService.invoke('SendMessage', 'someString');`

If it doesn't work, let me know!

**Comment by coommark** [comment]
Yes it works perfect. Thanks!!!
