### ISSUE TITLE
Disconnect and Reconnect

### ISSUE THREAD

**Issue by coommark** [sochix/angular-signalr#2]
Hey. I have been trying this and I love it. I added a few methods and will send to you to see if you can add them. Basically what I added is methods to return to the controller the connection states. I added a method to disconnect (stop) too. Let me describe the scenario.

I have an application-wide controller that I use to initialize the connection. This fires as soon as the user logs into the app. Now when the user logs out, I call the stop function I added. This works. Its a simple function that sets isInitialized to false, then calls connection.stop().

However, when the user re-logs in without refreshing the page, if I try to initialize and connect nothing happens. I can't reconnect unless I refresh the page. Do you have any suggestion how to handle this?

I love your project and will forward my additions as soon as I test all of them so you can include them. I am totally new to AngularJS and not too good with Javascript.

**Comment by sochix** [comment]
I think I understand your problem, but to be sure show me the code!

**Comment by coommark** [comment]
Here is the stopConnection function:

'''javascript
this.stopConnection = function() {
  if(this.isInitialized) {
     self.isInitialize = false;
     self.connection.stop();
  }
}'''

When I call it from logout(), it works and connection is closed. But when I try to reconnect it won't untill I refesh the page.

**Comment by coommark** [comment]
Hi! Have you tried? Attempted to close and open a connection from a page without refreshing? Just to add, on the server, the hub OnDisconnected receives the stop() resquest alright, the problem is that I can't connect again after I disconnect unless I manually refresh the browser.

**Comment by sochix** [comment]
Sorry, I have no time right now. But I'll try later

**Comment by sochix** [comment]
You could try do this:

``` javascript
 $.connection.hub.disconnected(function() {
   setTimeout(function() {
       $.connection.hub.start();
   }, 5000); // Restart connection after 5 seconds.
}); 
```

[See this article for details](http://www.asp.net/signalr/overview/guide-to-the-api/handling-connection-lifetime-events#clientdisconnect)

Also, after reading documentation I suggest that calling stop function on hub is a bad idea. Why you do it?
