### ISSUE TITLE
SignalR for angular dependencies

### ISSUE THREAD

**Issue by PterPmnta** [sochix/angular-signalr#3]
As I understand, to use this library, you must also use as dependence jquery and jquery plugin for signalR.

Then, if so the order of the files would be
### With jquery dependencies (Option 1)

```
Angular
Plugin-Angular-SignalR
Jquery
Plugin-Jquery-SignalR

```
### Without JQuery dependencies (Option 2)

```
Angular
Plugin-Angular-SignalR

```

What it's the correct way?

**Comment by sochix** [comment]
Yep, you-re right

**Comment by PterPmnta** [comment]
@sochix  i am confused, what option choose for development, edit the question, **option 1** or **option 2**

**Comment by sochix** [comment]
Option 1. Sorry, for not clear answer.

**Comment by PterPmnta** [comment]
@sochix  thanks for answer very fast, i am development **app** using **Ionic Framework**, ionic is based in **Angular JS**, i woud to know if work fine or maybe ocurred some error between JQuery and Angular
